local_dir := src/syscalls

local_c_source := \
	access.c \
	brk.c \
	close.c \
	exit.c \
	exit_group.c \
	fork.c \
	fstat64.c \
	futex.c \
	getcwd.c \
	getegid.c \
	geteuid.c \
	getgid.c \
	getpgrp.c \
	getpid.c \
	getppid.c \
	getuid.c \
	ioctl.c \
	lseek.c \
	lstat64.c \
	mmap.c \
	mprotect.c \
	open.c \
	read.c \
	readlink.c \
	rt_sigaction.c \
	tgkill.c \
	time.c \
	uname.c \
	waitpid.c \
	write.c

c_source += $(addprefix $(local_dir)/,$(local_c_source))
